// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace tp3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240927125858_migration_name")]
    partial class migration_name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tp3.Models.EntityFramework.Notation", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("utl_id")
                        .HasColumnOrder(0);

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("ser_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("not_note");

                    b.HasKey("UtilisateurId", "SerieId");

                    b.HasIndex("SerieId");

                    b.ToTable("t_j_notation_not", "public");
                });

            modelBuilder.Entity("tp3.Models.EntityFramework.Serie", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerieId"));

                    b.Property<int?>("AnneeCreation")
                        .HasColumnType("integer")
                        .HasColumnName("ser_anneecreation");

                    b.Property<int?>("NbEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("ser_nbepisodes");

                    b.Property<int?>("NbSaisons")
                        .HasColumnType("integer")
                        .HasColumnName("ser_nbsaisons");

                    b.Property<string>("Network")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ser_network");

                    b.Property<string>("Resume")
                        .HasColumnType("text")
                        .HasColumnName("ser_resume");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ser_titre");

                    b.HasKey("SerieId");

                    b.HasIndex("Titre");

                    b.ToTable("t_e_serie_ser", "public");
                });

            modelBuilder.Entity("tp3.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("utl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilisateurId"));

                    b.Property<string>("CodePostal")
                        .HasColumnType("char(5)")
                        .HasColumnName("utl_cp");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("utl_datecreation");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("utl_latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("utl_longitude");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("utl_mail");

                    b.Property<string>("Mobile")
                        .HasColumnType("char(10)")
                        .HasColumnName("utl_mobile");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_nom");

                    b.Property<string>("Pays")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_pays");

                    b.Property<string>("Prenom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_prenom");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("utl_pwd");

                    b.Property<string>("Rue")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("utl_rue");

                    b.Property<string>("Ville")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("utl_ville");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("t_e_utilisateur_utl", "public");
                });

            modelBuilder.Entity("tp3.Models.EntityFramework.Notation", b =>
                {
                    b.HasOne("tp3.Models.EntityFramework.Serie", "SerieNotee")
                        .WithMany("NotesSerie")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tp3.Models.EntityFramework.Utilisateur", "UtilisateurNotant")
                        .WithMany("NotesUtilisateur")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerieNotee");

                    b.Navigation("UtilisateurNotant");
                });

            modelBuilder.Entity("tp3.Models.EntityFramework.Serie", b =>
                {
                    b.Navigation("NotesSerie");
                });

            modelBuilder.Entity("tp3.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("NotesUtilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
